# Generated by Django 4.0.3 on 2022-04-30 21:35

from django.db import migrations
import el_tinto.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', el_tinto.users.models.UserManager()),
            ],
        ),
    ]
