# Generated by Django 4.0.3 on 2022-05-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name'),
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
    ]
