# Generated by Django 4.0.3 on 2022-06-12 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsuscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boring', models.BooleanField(default=False)),
                ('invasive', models.BooleanField(default=False)),
                ('variety', models.BooleanField(default=False)),
                ('not_used', models.BooleanField(default=False)),
                ('other_email', models.BooleanField(default=False)),
                ('recomendation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
