# Generated by Django 4.0.3 on 2022-08-16 01:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20220616_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unsuscribe',
            old_name='recomendation',
            new_name='recommendation',
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_email_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), blank=True, default=list, size=None),
        ),
    ]
