# Generated by Django 4.0.3 on 2022-08-16 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20220501_1302'),
        ('users', '0007_rename_recomendation_unsuscribe_recommendation_and_more'),
    ]

    operations = [
    ]
