# Generated by Django 4.0.3 on 2023-03-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_best_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_time',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='i',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='invite',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='user',
            name='size_group',
            field=models.CharField(default='', max_length=2),
        ),
    ]
