# Generated by Django 4.0.3 on 2023-05-29 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('398d0ef0-fe47-11ed-87f3-0242ac130004'), unique=True),
        ),
    ]
