# Generated by Django 4.0.3 on 2023-06-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='missing_sunday_mails',
            field=models.SmallIntegerField(default=4),
        ),
    ]
