# Generated by Django 4.1.9 on 2023-06-21 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0027_alter_mail_type_alter_mail_version'),
        ('users', '0018_user_missing_sunday_mails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='medium',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='utm_source',
            field=models.CharField(blank=True, choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('whatsapp', 'Whatsapp')], default='', max_length=25),
        ),
        migrations.CreateModel(
            name='UserVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SP', 'Suscripción'), ('RH', 'Centro de referidos')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mail', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mails.mail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserButtonsInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(blank=True, default='', max_length=25)),
                ('type', models.CharField(choices=[('TW', 'Twitter'), ('FB', 'Facebook'), ('WP', 'Whatsapp')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.uservisits')),
            ],
        ),
    ]
