# Generated by Django 4.1.9 on 2023-06-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_medium_user_utm_source_uservisits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbuttonsinteractions',
            name='type',
            field=models.CharField(choices=[('TW', 'Twitter'), ('FB', 'Facebook'), ('WP', 'Whatsapp'), ('CP', 'Copy & paste')], max_length=4),
        ),
    ]
