# Generated by Django 3.2.20 on 2023-07-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_userbuttonsinteractions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='utm_source',
            field=models.CharField(blank=True, choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('whatsapp', 'Whatsapp'), ('instagram', 'Instagram')], default='', max_length=25),
        ),
    ]
