# Generated by Django 4.1.10 on 2023-08-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_utm_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dispatch_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.SmallIntegerField(choices=[(0, 'Regular'), (1, 'Semilla de café'), (2, 'Grano de café'), (3, 'Tinto'), (4, 'Café de exportación')], default=0),
        ),
    ]
