# Generated by Django 4.1.10 on 2023-09-27 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_dispatch_time_user_tier'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='tier',
        ),
        migrations.AddField(
            model_name='user',
            name='tzinfo',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.CreateModel(
            name='UserTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.SmallIntegerField(choices=[(1, 'Grano de café'), (2, 'Café molido'), (3, 'Tinto'), (4, 'Café de exportación')])),
                ('missing_sunday_mails', models.PositiveSmallIntegerField(default=0)),
                ('will_renew', models.BooleanField(default=True)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField()),
                ('parent_tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_tiers', to='users.usertier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
