# Generated by Django 4.1.10 on 2023-09-03 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0002_alter_stripepayment_amount_alter_stripepayment_user_and_more'),
        ('users', '0022_user_dispatch_time_user_tier'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='tier',
        ),
        migrations.CreateModel(
            name='UserTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.SmallIntegerField(choices=[(1, 'Semilla de café'), (2, 'Grano de café'), (3, 'Tinto'), (4, 'Café de exportación')])),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_to', models.DateTimeField()),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stripe.stripepayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
