# Generated by Django 4.1.10 on 2023-10-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_managers_remove_user_tier_user_tzinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sunday_mails_prize_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
