# Generated by Django 4.1.10 on 2023-11-28 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0031_maillinks'),
        ('users', '0024_user_sunday_mails_prize_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLinkInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mails.maillinks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
