version: '3.9'
services:
  postgres:
    image: postgres:13.6-alpine
    environment:
      POSTGRES_PASSWORD: local
  django:
    restart: always
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
#  celery:
#    build: ./
#    command: celery --app=el_tinto.mails worker --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
#    volumes:
#      - ./:/code
#    env_file: .env
#    depends_on:
#      - django
#  redis:
#    image: redis:5.0.7
#  documentation:
#    restart: always
#    build: ./
#    command: "mkdocs serve"
#    volumes:
#      - ./:/code
#    ports:
#      - "8001:8001"
