site_name: El Tinto
site_description: Daily newsletter for Colombian tintos.
repo_url: https://github.com/charliebgood/el_tinto
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/charliebgood">charliebgood</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
