# Generated by Django 4.0.3 on 2023-02-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('site', models.CharField(choices=[('COWORKINGS', 'Co-workings'), ('RESTAURANTS', 'Restaurantes'), ('LIBRARIES', 'Bibliotecas'), ('THEATERS', 'Teatros'), ('CAFES', 'Cafés')], default='', max_length=15)),
                ('request_info', models.TextField(default='')),
            ],
        ),
    ]
