# Generated by Django 4.0.3 on 2022-04-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='subject',
            field=models.TextField(default='', max_length=256),
        ),
    ]
