# Generated by Django 4.0.3 on 2022-04-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_alter_mail_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='test_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
