# Generated by Django 4.0.3 on 2022-04-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_mail_test_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Test', 'Test'), ('Promotion', 'Promotion')], max_length=15),
        ),
    ]
