# Generated by Django 4.0.3 on 2022-04-26 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mails', '0005_alter_mail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mail',
            name='type',
            field=models.CharField(choices=[('Daily', 'Diario'), ('Test', 'Testeo'), ('Promotion', 'Promoción')], max_length=15),
        ),
    ]
