# Generated by Django 4.0.3 on 2022-04-26 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mails', '0006_alter_mail_created_by_alter_mail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='version',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=15),
        ),
        migrations.AlterField(
            model_name='mail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sended_emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
