# Generated by Django 4.0.3 on 2022-05-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0010_sendedemails_mail_recipients_alter_mail_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendedemails',
            name='opened_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
