# Generated by Django 4.0.3 on 2022-06-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0011_alter_sendedemails_opened_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='tweet',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
    ]
