# Generated by Django 4.0.3 on 2022-07-13 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mails', '0012_mail_tweet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendedEmails',
            new_name='SentEmails',
        ),
        migrations.AlterField(
            model_name='mail',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SentEmailsInteractions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TW', 'Twitter'), ('FB', 'Facebook'), ('WP', 'Whatsapp'), ('WBP', 'Web page'), ('OT', 'Other')], default='', max_length=3)),
                ('link', models.TextField()),
                ('click_date', models.DateTimeField(auto_now_add=True)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mails.mail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clicks_tracking',
            },
        ),
    ]
