# Generated by Django 4.0.3 on 2022-07-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0013_rename_sendedemails_sentemails_alter_mail_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='version',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('DEFAULT', 'Testeo en blanco')], default='A', max_length=15),
        ),
    ]
