# Generated by Django 4.0.3 on 2022-09-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0017_alter_mail_subject_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='subject_message',
            field=models.CharField(blank=True, default='', help_text='Texto que acompaña al subject', max_length=256),
        ),
    ]
