# Generated by Django 4.0.3 on 2022-09-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0018_alter_mail_subject_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='sent_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
