# Generated by Django 4.0.3 on 2022-10-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0019_mail_sent_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='type',
            field=models.CharField(choices=[('Daily', 'Diario'), ('Test', 'Testeo'), ('Promotion', 'Promoción'), ('Welcome', 'Bienvenida')], max_length=15),
        ),
    ]
