# Generated by Django 4.0.3 on 2022-12-27 00:08

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tintos', '0001_initial'),
        ('mails', '0020_alter_mail_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('label', models.CharField(max_length=120, unique=True)),
                ('file_name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='mail',
            name='tinto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail', to='tintos.tinto'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='html',
            field=tinymce.models.HTMLField(),
        ),
    ]
