# Generated by Django 4.0.3 on 2023-01-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0021_templates_mail_tinto_alter_mail_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='tweet',
            field=models.CharField(default='', help_text='256 characters max', max_length=256),
        ),
    ]
