# Generated by Django 4.0.3 on 2023-01-24 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tintos', '0002_alter_newstype_options_alter_tinto_options'),
        ('mails', '0022_alter_mail_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemailsinteractions',
            name='tinto_block_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='tintos.tintoblocksentries'),
        ),
        migrations.AlterField(
            model_name='sentemailsinteractions',
            name='mail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='mails.mail'),
        ),
        migrations.AlterField(
            model_name='sentemailsinteractions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
