# Generated by Django 4.0.3 on 2023-02-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0023_sentemailsinteractions_tinto_block_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemailsinteractions',
            name='type',
            field=models.CharField(choices=[('TW', 'Twitter'), ('FB', 'Facebook'), ('WP', 'Whatsapp'), ('WBP', 'Web page'), ('OT', 'Other'), ('VAKI', 'Vaki')], default='', max_length=4),
        ),
    ]
