# Generated by Django 4.0.3 on 2023-04-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0024_alter_sentemailsinteractions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='type',
            field=models.CharField(choices=[('Daily', 'Diario'), ('Test', 'Testeo'), ('Promotion', 'Promoción'), ('Welcome', 'Bienvenida'), ('Milestone', 'Meta de referidos')], max_length=15),
        ),
    ]
