# Generated by Django 4.0.3 on 2023-05-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0025_alter_mail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='type',
            field=models.CharField(choices=[('Daily', 'Diario'), ('Test', 'Testeo'), ('Promotion', 'Promoción'), ('Welcome', 'Bienvenida'), ('Milestone', 'Meta de referidos'), ('Daily not sent', 'No enviado'), ('Preferred days', 'Cambiar días preferidos')], max_length=15),
        ),
    ]
