# Generated by Django 4.0.3 on 2023-06-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0026_alter_mail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='type',
            field=models.CharField(choices=[('Daily', 'Diario'), ('Test', 'Testeo'), ('Promotion', 'Promoción'), ('Welcome', 'Bienvenida'), ('Milestone', 'Meta de referidos'), ('Daily not sent', 'No enviado'), ('Preferred days', 'Cambiar días preferidos'), ('Sunday', 'Dominguero')], max_length=15),
        ),
        migrations.AlterField(
            model_name='mail',
            name='version',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('SUNDAY NO PRIZE', 'Dominguero sin premios'), ('DEFAULT', 'Testeo en blanco')], default='A', max_length=15),
        ),
    ]
