# Generated by Django 4.1.10 on 2023-09-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ses_sns', '0001_initial'),
        ('mails', '0027_alter_mail_type_alter_mail_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemails',
            name='sns_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ses_sns.snsnotification'),
        ),
    ]
