# Generated by Django 4.1.10 on 2023-10-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0028_sentemails_sns_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='sponsor_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mail',
            name='sponsor_web_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mail',
            name='type',
            field=models.CharField(choices=[('Daily', 'Diario'), ('Test', 'Testeo'), ('Promotion', 'Promoción'), ('Welcome', 'Bienvenida'), ('Milestone', 'Meta de referidos'), ('Preferred days', 'Cambiar días preferidos'), ('Taste club', 'Club de Cata'), ('Sunday', 'Dominguero')], max_length=15),
        ),
    ]
