# Generated by Django 4.1.10 on 2023-10-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0029_mail_sponsor_image_url_mail_sponsor_web_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='sponsor_image_url_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
