# Generated by Django 4.1.10 on 2023-11-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0030_mail_sponsor_image_url_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_link', models.TextField()),
                ('code', models.TextField(blank=True, default='')),
            ],
        ),
    ]
