# Generated by Django 4.1.10 on 2023-09-27 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0023_alter_user_managers_remove_user_tier_user_tzinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Amount of payment in cents')),
                ('currency', models.CharField(help_text='Currency of payment', max_length=3)),
                ('subscription', models.CharField(default='', help_text='Subscription related to payment', max_length=40)),
                ('created', models.DateField(auto_now_add=True)),
                ('json', models.JSONField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payments', to=settings.AUTH_USER_MODEL)),
                ('user_tier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.usertier')),
            ],
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=4, null=True)),
                ('address_1', models.CharField(blank=True, max_length=128, null=True)),
                ('address_2', models.CharField(blank=True, max_length=128, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('json', models.JSONField()),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stripe.stripepayment')),
            ],
        ),
    ]
