# Generated by Django 4.1.10 on 2023-09-03 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.SmallIntegerField(choices=[(1, 'Semilla de café'), (2, 'Grano de café'), (3, 'Tinto'), (4, 'Café de exportación')], default=1)),
                ('amount', models.PositiveSmallIntegerField(help_text='Amount of payment')),
                ('currency', models.CharField(help_text='Currency of payment', max_length=3)),
                ('json', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
