# Generated by Django 4.0.3 on 2022-12-11 18:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tinto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('html', tinymce.models.HTMLField(blank=True, default='')),
                ('email_dispatch_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tinto',
                'verbose_name_plural': 'Tintos',
                'ordering': ('email_dispatch_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TintoBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', tinymce.models.HTMLField()),
                ('title', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('News', 'Noticias'), ('Advertisement', 'Publicidad'), ('Recommendation', 'Recomendación'), ('Others', 'Otros')], default='News', max_length=30)),
                ('subtype', models.CharField(choices=[('National Politics', 'Política nacional'), ('International Politics', 'Política internacional'), ('Economics', 'Económica'), ('Sports', 'Deportes'), ('Culture', 'Cultural')], default='National Politics', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloque de Tinto',
                'verbose_name_plural': 'Bloques de Tinto',
                'ordering': ('created_at', 'type', 'subtype', 'title'),
            },
        ),
        migrations.CreateModel(
            name='TintoBlocksEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('show_share_buttons', models.BooleanField(default=False)),
                ('show_rate_buttons', models.BooleanField(default=False)),
                ('show_reading_time', models.BooleanField(default=False)),
                ('like', models.BooleanField(blank=True, null=True)),
                ('tinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tintos.tinto')),
                ('tinto_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tintos.tintoblocks')),
            ],
            options={
                'verbose_name': 'Entrada de bloques',
                'verbose_name_plural': 'Entradas de bloques',
                'ordering': ('tinto__created_at', 'position'),
                'unique_together': {('tinto', 'position')},
            },
        ),
        migrations.AddField(
            model_name='tinto',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='tintos', through='tintos.TintoBlocksEntries', to='tintos.tintoblocks'),
        ),
    ]
