# Generated by Django 4.0.3 on 2022-12-27 00:08

import django.core.validators
from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('label', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de noticia',
                'verbose_name_plural': 'Tipos de noticia',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tinto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('html', tinymce.models.HTMLField(blank=True, default='')),
                ('email_dispatch_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tinto',
                'verbose_name_plural': 'Tintos',
                'ordering': ('email_dispatch_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TintoBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', tinymce.models.HTMLField()),
                ('title', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tintos.newstype')),
            ],
            options={
                'verbose_name': 'Bloque de Tinto',
                'verbose_name_plural': 'Bloques de Tinto',
                'ordering': ('created_at', 'type', 'news_type', 'title'),
            },
        ),
        migrations.CreateModel(
            name='TintoBlockType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('label', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Bloque',
                'verbose_name_plural': 'Tipos de Bloque',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TintoBlocksEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_html', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('show_share_buttons', models.BooleanField(default=False)),
                ('show_rate_buttons', models.BooleanField(default=False)),
                ('show_reading_time', models.BooleanField(default=False)),
                ('like', models.BooleanField(blank=True, null=True)),
                ('break_line', models.BooleanField(default=True)),
                ('tinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tintos.tinto')),
                ('tinto_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tintos.tintoblocks')),
            ],
            options={
                'verbose_name': 'Entrada de bloques',
                'verbose_name_plural': 'Entradas de bloques',
                'ordering': ('tinto__created_at', 'position'),
            },
        ),
        migrations.AddField(
            model_name='tintoblocks',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tintos.tintoblocktype'),
        ),
        migrations.AddField(
            model_name='tinto',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='tintos', through='tintos.TintoBlocksEntries', to='tintos.tintoblocks'),
        ),
        migrations.AddConstraint(
            model_name='tintoblocksentries',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('tinto', 'position'), name='unique_position_in_tinto'),
        ),
    ]
