# Generated by Django 4.0.3 on 2023-01-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tintos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstype',
            options={'ordering': ('name',), 'verbose_name': 'Tipo de historia', 'verbose_name_plural': 'Tipos de historias'},
        ),
        migrations.AlterModelOptions(
            name='tinto',
            options={'ordering': ('-email_dispatch_date', 'created_at'), 'verbose_name': 'Tinto', 'verbose_name_plural': 'Tintos'},
        ),
    ]
