# Generated by Django 4.0.3 on 2023-05-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tintos', '0002_alter_newstype_options_alter_tinto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tintoblocks',
            name='title_slug',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
