# Generated by Django 4.0.3 on 2023-05-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tintos', '0003_tintoblocks_title_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tintoblocks',
            options={'ordering': ('-created_at', 'type', 'news_type', 'title'), 'verbose_name': 'Bloque de Tinto', 'verbose_name_plural': 'Bloques de Tinto'},
        ),
    ]
